//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Step
    {
        public Step()
        {
            this.CurrentSteps = new HashSet<CurrentStep>();
        }
    
        public int Id { get; set; }
        public int DocumentId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> Status { get; set; }
        public int SerialNumber { get; set; }
    
        public virtual ICollection<CurrentStep> CurrentSteps { get; set; }
        public virtual Document Document { get; set; }
        public virtual User User { get; set; }
    }
}
